// Service de conversion de devises
class CurrencyService {
  private cache: Map<string, { rates: any; timestamp: number }> = new Map();
  private readonly CACHE_DURATION = 24 * 60 * 60 * 1000; // 24 heures

  // Taux de change de base (USD vers autres devises)
  private baseRates: { [key: string]: number } = {
    'USD': 1,
    'EUR': 0.85,
    'GBP': 0.73,
    'CAD': 1.25,
    'AUD': 1.35,
    'CHF': 0.88,
    'JPY': 110,
    'CNY': 6.45,
    'INR': 75,
    'BRL': 5.2,
    'MAD': 9.0,
    'AED': 3.67,
    'SAR': 3.75,
    'EGP': 15.7,
    'ZAR': 14.5,
    'KRW': 1180,
    'SGD': 1.35,
    'HKD': 7.8,
    'NZD': 1.4,
    'SEK': 8.5,
    'NOK': 8.8,
    'DKK': 6.3,
    'PLN': 3.9,
    'CZK': 21.5,
    'HUF': 300,
    'RON': 4.2,
    'BGN': 1.66,
    'HRK': 6.4,
    'RSD': 100,
    'TRY': 8.5,
    'RUB': 75,
    'UAH': 27,
    'ILS': 3.2,
    'QAR': 3.64,
    'KWD': 0.3,
    'BHD': 0.38,
    'OMR': 0.38,
    'JOD': 0.71,
    'LBP': 1500,
    'PKR': 160,
    'BDT': 85,
    'LKR': 200,
    'NPR': 120,
    'AFN': 80,
    'THB': 33,
    'VND': 23000,
    'IDR': 14300,
    'MYR': 4.2,
    'PHP': 50,
    'TWD': 28,
    'MXN': 20,
    'ARS': 100,
    'CLP': 800,
    'COP': 3800,
    'PEN': 3.7,
    'UYU': 43,
    'PYG': 7000,
    'BOB': 6.9,
    'VES': 4000000,
    'GYD': 209,
    'SRD': 21,
    'DZD': 135,
    'TND': 2.8,
    'LYD': 4.5,
    'SDG': 55,
    'ETB': 44,
    'KES': 110,
    'UGX': 3500,
    'TZS': 2300,
    'GHS': 6.1,
    'NGN': 410,
    'BWP': 11,
    'NAD': 14.5,
    'ZWL': 85,
    'ZMW': 18,
    'MWK': 820,
    'MZN': 64,
    'AOA': 650,
    'XAF': 560,
    'XOF': 560,
    'CDF': 2000,
    'STN': 20,
    'GNF': 10200,
    'SLE': 18,
    'LRD': 150,
    'GMD': 52,
    'MRU': 36,
    'CVE': 100,
    'KMF': 440,
    'SCR': 13,
    'MUR': 42,
    'MGA': 4000,
    'LSL': 14.5,
    'SZL': 14.5,
    'BYN': 2.5,
    'MDL': 17.5,
    'GEL': 3.1,
    'AMD': 520,
    'AZN': 1.7,
    'KZT': 425,
    'UZS': 10750,
    'KGS': 85,
    'TJS': 11.3,
    'TMT': 3.5,
    'MVR': 15.4,
    'MMK': 1800,
    'LAK': 9500,
    'KHR': 4100,
    'BND': 1.35,
    'MOP': 8,
    'MNT': 2850,
    'KPW': 900,
    'YER': 250,
    'IQD': 1460,
    'IRR': 42000,
    'SYP': 2500,
    'ISK': 130,
    'ALL': 105,
    'MKD': 52,
    'BAM': 1.66
  };

  // Convertir un montant d'une devise à une autre
  public convert(amount: number, fromCurrency: string, toCurrency: string): number {
    if (fromCurrency === toCurrency) {
      return amount;
    }

    // Convertir d'abord vers USD, puis vers la devise cible
    const fromRate = this.baseRates[fromCurrency] || 1;
    const toRate = this.baseRates[toCurrency] || 1;

    // Montant en USD
    const amountInUSD = amount / fromRate;
    
    // Montant dans la devise cible
    const convertedAmount = amountInUSD * toRate;

    return Math.round(convertedAmount * 100) / 100; // Arrondir à 2 décimales
  }

  // Obtenir le taux de change entre deux devises
  public getExchangeRate(fromCurrency: string, toCurrency: string): number {
    if (fromCurrency === toCurrency) {
      return 1;
    }

    const fromRate = this.baseRates[fromCurrency] || 1;
    const toRate = this.baseRates[toCurrency] || 1;

    return toRate / fromRate;
  }

  // Formater un montant avec le symbole de la devise
  public formatAmount(amount: number, currency: string): string {
    const symbols: { [key: string]: string } = {
      'USD': '$',
      'EUR': '€',
      'GBP': '£',
      'CAD': 'C$',
      'AUD': 'A$',
      'CHF': 'CHF',
      'JPY': '¥',
      'CNY': '¥',
      'INR': '₹',
      'BRL': 'R$',
      'MAD': 'MAD',
      'AED': 'AED',
      'SAR': 'SAR',
      'EGP': 'EGP',
      'ZAR': 'R',
      'KRW': '₩',
      'SGD': 'S$',
      'HKD': 'HK$',
      'NZD': 'NZ$',
      'SEK': 'kr',
      'NOK': 'kr',
      'DKK': 'kr',
      'PLN': 'zł',
      'CZK': 'Kč',
      'HUF': 'Ft',
      'RON': 'lei',
      'BGN': 'лв',
      'HRK': 'kn',
      'RSD': 'дин',
      'TRY': '₺',
      'RUB': '₽',
      'UAH': '₴',
      'ILS': '₪',
      'QAR': 'QR',
      'KWD': 'KD',
      'BHD': 'BD',
      'OMR': 'OMR',
      'JOD': 'JD',
      'LBP': 'L£',
      'PKR': '₨',
      'BDT': '৳',
      'LKR': 'Rs',
      'NPR': 'Rs',
      'AFN': '؋',
      'THB': '฿',
      'VND': '₫',
      'IDR': 'Rp',
      'MYR': 'RM',
      'PHP': '₱',
      'TWD': 'NT$',
      'MXN': '$',
      'ARS': '$',
      'CLP': '$',
      'COP': '$',
      'PEN': 'S/',
      'UYU': '$U',
      'PYG': '₲',
      'BOB': 'Bs',
      'VES': 'Bs.S',
      'GYD': 'G$',
      'SRD': '$',
      'DZD': 'د.ج',
      'TND': 'د.ت',
      'LYD': 'ل.د',
      'SDG': 'ج.س',
      'ETB': 'Br',
      'KES': 'KSh',
      'UGX': 'USh',
      'TZS': 'TSh',
      'GHS': '₵',
      'NGN': '₦',
      'BWP': 'P',
      'NAD': 'N$',
      'ZWL': 'Z$',
      'ZMW': 'ZK',
      'MWK': 'MK',
      'MZN': 'MT',
      'AOA': 'Kz',
      'XAF': 'FCFA',
      'XOF': 'CFA',
      'CDF': 'FC',
      'STN': 'Db',
      'GNF': 'FG',
      'SLE': 'Le',
      'LRD': 'L$',
      'GMD': 'D',
      'MRU': 'UM',
      'CVE': '$',
      'KMF': 'CF',
      'SCR': '₨',
      'MUR': '₨',
      'MGA': 'Ar',
      'LSL': 'L',
      'SZL': 'L',
      'BYN': 'Br',
      'MDL': 'L',
      'GEL': '₾',
      'AMD': '֏',
      'AZN': '₼',
      'KZT': '₸',
      'UZS': 'лв',
      'KGS': 'лв',
      'TJS': 'SM',
      'TMT': 'T',
      'MVR': 'Rf',
      'MMK': 'K',
      'LAK': '₭',
      'KHR': '៛',
      'BND': 'B$',
      'MOP': 'MOP$',
      'MNT': '₮',
      'KPW': '₩',
      'YER': '﷼',
      'IQD': 'ع.د',
      'IRR': '﷼',
      'SYP': '£',
      'ISK': 'kr',
      'ALL': 'L',
      'MKD': 'ден',
      'BAM': 'КМ'
    };

    const symbol = symbols[currency] || currency;
    return `${symbol} ${amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  }

  // Formater un montant avec le symbole de la devise (alias pour formatAmount)
  public formatCurrency(amount: number, currency: string): string {
    return this.formatAmount(amount, currency);
  }

  // Convertir un montant d'une devise à une autre (alias pour convert)
  public convertCurrency(amount: number, fromCurrency: string, toCurrency: string): { from: string; to: string; amount: number; convertedAmount: number; rate: number; lastUpdated: number } {
    const convertedAmount = this.convert(amount, fromCurrency, toCurrency);
    const rate = this.getExchangeRate(fromCurrency, toCurrency);
    
    return {
      from: fromCurrency,
      to: toCurrency,
      amount,
      convertedAmount,
      rate,
      lastUpdated: Date.now()
    };
  }

  // Obtenir la devise d'un pays
  public getCountryCurrency(country: string): string {
    const countryCurrencies: { [key: string]: string } = {
      'United States': 'USD',
      'Canada': 'CAD',
      'United Kingdom': 'GBP',
      'France': 'EUR',
      'Germany': 'EUR',
      'Italy': 'EUR',
      'Spain': 'EUR',
      'Netherlands': 'EUR',
      'Belgium': 'EUR',
      'Austria': 'EUR',
      'Portugal': 'EUR',
      'Ireland': 'EUR',
      'Finland': 'EUR',
      'Luxembourg': 'EUR',
      'Slovenia': 'EUR',
      'Slovakia': 'EUR',
      'Estonia': 'EUR',
      'Latvia': 'EUR',
      'Lithuania': 'EUR',
      'Malta': 'EUR',
      'Cyprus': 'EUR',
      'Japan': 'JPY',
      'China': 'CNY',
      'India': 'INR',
      'Brazil': 'BRL',
      'Morocco': 'MAD',
      'United Arab Emirates': 'AED',
      'Saudi Arabia': 'SAR',
      'Egypt': 'EGP',
      'South Africa': 'ZAR',
      'South Korea': 'KRW',
      'Singapore': 'SGD',
      'Hong Kong': 'HKD',
      'Australia': 'AUD',
      'New Zealand': 'NZD',
      'Sweden': 'SEK',
      'Norway': 'NOK',
      'Denmark': 'DKK',
      'Poland': 'PLN',
      'Czech Republic': 'CZK',
      'Hungary': 'HUF',
      'Romania': 'RON',
      'Bulgaria': 'BGN',
      'Croatia': 'HRK',
      'Serbia': 'RSD',
      'Turkey': 'TRY',
      'Russia': 'RUB',
      'Ukraine': 'UAH',
      'Israel': 'ILS',
      'Qatar': 'QAR',
      'Kuwait': 'KWD',
      'Bahrain': 'BHD',
      'Oman': 'OMR',
      'Jordan': 'JOD',
      'Lebanon': 'LBP',
      'Pakistan': 'PKR',
      'Bangladesh': 'BDT',
      'Sri Lanka': 'LKR',
      'Nepal': 'NPR',
      'Afghanistan': 'AFN',
      'Thailand': 'THB',
      'Vietnam': 'VND',
      'Indonesia': 'IDR',
      'Malaysia': 'MYR',
      'Philippines': 'PHP',
      'Taiwan': 'TWD',
      'Mexico': 'MXN',
      'Argentina': 'ARS',
      'Chile': 'CLP',
      'Colombia': 'COP',
      'Peru': 'PEN',
      'Uruguay': 'UYU',
      'Paraguay': 'PYG',
      'Bolivia': 'BOB',
      'Venezuela': 'VES',
      'Guyana': 'GYD',
      'Suriname': 'SRD',
      'Algeria': 'DZD',
      'Tunisia': 'TND',
      'Libya': 'LYD',
      'Sudan': 'SDG',
      'Ethiopia': 'ETB',
      'Kenya': 'KES',
      'Uganda': 'UGX',
      'Tanzania': 'TZS',
      'Ghana': 'GHS',
      'Nigeria': 'NGN',
      'Botswana': 'BWP',
      'Namibia': 'NAD',
      'Zimbabwe': 'ZWL',
      'Zambia': 'ZMW',
      'Malawi': 'MWK',
      'Mozambique': 'MZN',
      'Angola': 'AOA',
      'Cameroon': 'XAF',
      'Senegal': 'XOF',
      'Democratic Republic of the Congo': 'CDF',
      'São Tomé and Príncipe': 'STN',
      'Guinea': 'GNF',
      'Sierra Leone': 'SLE',
      'Liberia': 'LRD',
      'Gambia': 'GMD',
      'Mauritania': 'MRU',
      'Cape Verde': 'CVE',
      'Comoros': 'KMF',
      'Seychelles': 'SCR',
      'Mauritius': 'MUR',
      'Madagascar': 'MGA',
      'Lesotho': 'LSL',
      'Eswatini': 'SZL',
      'Belarus': 'BYN',
      'Moldova': 'MDL',
      'Georgia': 'GEL',
      'Armenia': 'AMD',
      'Azerbaijan': 'AZN',
      'Kazakhstan': 'KZT',
      'Uzbekistan': 'UZS',
      'Kyrgyzstan': 'KGS',
      'Tajikistan': 'TJS',
      'Turkmenistan': 'TMT',
      'Maldives': 'MVR',
      'Myanmar': 'MMK',
      'Laos': 'LAK',
      'Cambodia': 'KHR',
      'Brunei': 'BND',
      'Macau': 'MOP',
      'Mongolia': 'MNT',
      'North Korea': 'KPW',
      'Yemen': 'YER',
      'Iraq': 'IQD',
      'Iran': 'IRR',
      'Syria': 'SYP',
      'Iceland': 'ISK',
      'Albania': 'ALL',
      'North Macedonia': 'MKD',
      'Bosnia and Herzegovina': 'BAM'
    };

    return countryCurrencies[country] || 'USD';
  }

  // Obtenir toutes les devises supportées
  public getSupportedCurrencies(): string[] {
    return Object.keys(this.baseRates);
  }

  // Obtenir toutes les devises supportées avec leurs détails
  public getSupportedCurrenciesWithDetails(): Array<{code: string, name: string, symbol: string, flag: string}> {
    const currencyNames: { [key: string]: string } = {
      'USD': 'US Dollar',
      'EUR': 'Euro',
      'GBP': 'British Pound',
      'CAD': 'Canadian Dollar',
      'AUD': 'Australian Dollar',
      'CHF': 'Swiss Franc',
      'JPY': 'Japanese Yen',
      'CNY': 'Chinese Yuan',
      'INR': 'Indian Rupee',
      'BRL': 'Brazilian Real',
      'MAD': 'Moroccan Dirham',
      'AED': 'UAE Dirham',
      'SAR': 'Saudi Riyal',
      'EGP': 'Egyptian Pound',
      'ZAR': 'South African Rand',
      'KRW': 'South Korean Won',
      'SGD': 'Singapore Dollar',
      'HKD': 'Hong Kong Dollar',
      'NZD': 'New Zealand Dollar',
      'SEK': 'Swedish Krona',
      'NOK': 'Norwegian Krone',
      'DKK': 'Danish Krone',
      'PLN': 'Polish Zloty',
      'CZK': 'Czech Koruna',
      'HUF': 'Hungarian Forint',
      'RON': 'Romanian Leu',
      'BGN': 'Bulgarian Lev',
      'HRK': 'Croatian Kuna',
      'RSD': 'Serbian Dinar',
      'TRY': 'Turkish Lira',
      'RUB': 'Russian Ruble',
      'UAH': 'Ukrainian Hryvnia',
      'ILS': 'Israeli Shekel',
      'QAR': 'Qatari Riyal',
      'KWD': 'Kuwaiti Dinar',
      'BHD': 'Bahraini Dinar',
      'OMR': 'Omani Rial',
      'JOD': 'Jordanian Dinar',
      'LBP': 'Lebanese Pound',
      'PKR': 'Pakistani Rupee',
      'BDT': 'Bangladeshi Taka',
      'LKR': 'Sri Lankan Rupee',
      'NPR': 'Nepalese Rupee',
      'AFN': 'Afghan Afghani',
      'THB': 'Thai Baht',
      'VND': 'Vietnamese Dong',
      'IDR': 'Indonesian Rupiah',
      'MYR': 'Malaysian Ringgit',
      'PHP': 'Philippine Peso',
      'TWD': 'Taiwan Dollar',
      'MXN': 'Mexican Peso',
      'ARS': 'Argentine Peso',
      'CLP': 'Chilean Peso',
      'COP': 'Colombian Peso',
      'PEN': 'Peruvian Sol',
      'UYU': 'Uruguayan Peso',
      'PYG': 'Paraguayan Guarani',
      'BOB': 'Bolivian Boliviano',
      'VES': 'Venezuelan Bolivar',
      'GYD': 'Guyanese Dollar',
      'SRD': 'Surinamese Dollar',
      'DZD': 'Algerian Dinar',
      'TND': 'Tunisian Dinar',
      'LYD': 'Libyan Dinar',
      'SDG': 'Sudanese Pound',
      'ETB': 'Ethiopian Birr',
      'KES': 'Kenyan Shilling',
      'UGX': 'Ugandan Shilling',
      'TZS': 'Tanzanian Shilling',
      'GHS': 'Ghanaian Cedi',
      'NGN': 'Nigerian Naira',
      'BWP': 'Botswana Pula',
      'NAD': 'Namibian Dollar',
      'ZWL': 'Zimbabwean Dollar',
      'ZMW': 'Zambian Kwacha',
      'MWK': 'Malawian Kwacha',
      'MZN': 'Mozambican Metical',
      'AOA': 'Angolan Kwanza',
      'XAF': 'Central African CFA Franc',
      'XOF': 'West African CFA Franc',
      'CDF': 'Congolese Franc',
      'STN': 'São Tomé and Príncipe Dobra',
      'GNF': 'Guinean Franc',
      'SLE': 'Sierra Leonean Leone',
      'LRD': 'Liberian Dollar',
      'GMD': 'Gambian Dalasi',
      'MRU': 'Mauritanian Ouguiya',
      'CVE': 'Cape Verdean Escudo',
      'KMF': 'Comorian Franc',
      'SCR': 'Seychellois Rupee',
      'MUR': 'Mauritian Rupee',
      'MGA': 'Malagasy Ariary',
      'LSL': 'Lesotho Loti',
      'SZL': 'Swazi Lilangeni',
      'BYN': 'Belarusian Ruble',
      'MDL': 'Moldovan Leu',
      'GEL': 'Georgian Lari',
      'AMD': 'Armenian Dram',
      'AZN': 'Azerbaijani Manat',
      'KZT': 'Kazakhstani Tenge',
      'UZS': 'Uzbekistani Som',
      'KGS': 'Kyrgyzstani Som',
      'TJS': 'Tajikistani Somoni',
      'TMT': 'Turkmenistani Manat',
      'MVR': 'Maldivian Rufiyaa',
      'MMK': 'Myanmar Kyat',
      'LAK': 'Lao Kip',
      'KHR': 'Cambodian Riel',
      'BND': 'Brunei Dollar',
      'MOP': 'Macanese Pataca',
      'MNT': 'Mongolian Tugrik',
      'KPW': 'North Korean Won',
      'YER': 'Yemeni Rial',
      'IQD': 'Iraqi Dinar',
      'IRR': 'Iranian Rial',
      'SYP': 'Syrian Pound',
      'ISK': 'Icelandic Krona',
      'ALL': 'Albanian Lek',
      'MKD': 'Macedonian Denar',
      'BAM': 'Bosnia and Herzegovina Convertible Mark'
    };

    const symbols: { [key: string]: string } = {
      'USD': '$',
      'EUR': '€',
      'GBP': '£',
      'CAD': 'C$',
      'AUD': 'A$',
      'CHF': 'CHF',
      'JPY': '¥',
      'CNY': '¥',
      'INR': '₹',
      'BRL': 'R$',
      'MAD': 'MAD',
      'AED': 'AED',
      'SAR': 'SAR',
      'EGP': 'EGP',
      'ZAR': 'R',
      'KRW': '₩',
      'SGD': 'S$',
      'HKD': 'HK$',
      'NZD': 'NZ$',
      'SEK': 'kr',
      'NOK': 'kr',
      'DKK': 'kr',
      'PLN': 'zł',
      'CZK': 'Kč',
      'HUF': 'Ft',
      'RON': 'lei',
      'BGN': 'лв',
      'HRK': 'kn',
      'RSD': 'дин',
      'TRY': '₺',
      'RUB': '₽',
      'UAH': '₴',
      'ILS': '₪',
      'QAR': 'QR',
      'KWD': 'KD',
      'BHD': 'BD',
      'OMR': 'OMR',
      'JOD': 'JD',
      'LBP': 'L£',
      'PKR': '₨',
      'BDT': '৳',
      'LKR': 'Rs',
      'NPR': 'Rs',
      'AFN': '؋',
      'THB': '฿',
      'VND': '₫',
      'IDR': 'Rp',
      'MYR': 'RM',
      'PHP': '₱',
      'TWD': 'NT$',
      'MXN': '$',
      'ARS': '$',
      'CLP': '$',
      'COP': '$',
      'PEN': 'S/',
      'UYU': '$U',
      'PYG': '₲',
      'BOB': 'Bs',
      'VES': 'Bs.S',
      'GYD': 'G$',
      'SRD': '$',
      'DZD': 'د.ج',
      'TND': 'د.ت',
      'LYD': 'ل.د',
      'SDG': 'ج.س',
      'ETB': 'Br',
      'KES': 'KSh',
      'UGX': 'USh',
      'TZS': 'TSh',
      'GHS': '₵',
      'NGN': '₦',
      'BWP': 'P',
      'NAD': 'N$',
      'ZWL': 'Z$',
      'ZMW': 'ZK',
      'MWK': 'MK',
      'MZN': 'MT',
      'AOA': 'Kz',
      'XAF': 'FCFA',
      'XOF': 'CFA',
      'CDF': 'FC',
      'STN': 'Db',
      'GNF': 'FG',
      'SLE': 'Le',
      'LRD': 'L$',
      'GMD': 'D',
      'MRU': 'UM',
      'CVE': '$',
      'KMF': 'CF',
      'SCR': '₨',
      'MUR': '₨',
      'MGA': 'Ar',
      'LSL': 'L',
      'SZL': 'L',
      'BYN': 'Br',
      'MDL': 'L',
      'GEL': '₾',
      'AMD': '֏',
      'AZN': '₼',
      'KZT': '₸',
      'UZS': 'лв',
      'KGS': 'лв',
      'TJS': 'SM',
      'TMT': 'T',
      'MVR': 'Rf',
      'MMK': 'K',
      'LAK': '₭',
      'KHR': '៛',
      'BND': 'B$',
      'MOP': 'MOP$',
      'MNT': '₮',
      'KPW': '₩',
      'YER': '﷼',
      'IQD': 'ع.د',
      'IRR': '﷼',
      'SYP': '£',
      'ISK': 'kr',
      'ALL': 'L',
      'MKD': 'ден',
      'BAM': 'КМ'
    };

    const flags: { [key: string]: string } = {
      'USD': '🇺🇸',
      'EUR': '🇪🇺',
      'GBP': '🇬🇧',
      'CAD': '🇨🇦',
      'AUD': '🇦🇺',
      'CHF': '🇨🇭',
      'JPY': '🇯🇵',
      'CNY': '🇨🇳',
      'INR': '🇮🇳',
      'BRL': '🇧🇷',
      'MAD': '🇲🇦',
      'AED': '🇦🇪',
      'SAR': '🇸🇦',
      'EGP': '🇪🇬',
      'ZAR': '🇿🇦',
      'KRW': '🇰🇷',
      'SGD': '🇸🇬',
      'HKD': '🇭🇰',
      'NZD': '🇳🇿',
      'SEK': '🇸🇪',
      'NOK': '🇳🇴',
      'DKK': '🇩🇰',
      'PLN': '🇵🇱',
      'CZK': '🇨🇿',
      'HUF': '🇭🇺',
      'RON': '🇷🇴',
      'BGN': '🇧🇬',
      'HRK': '🇭🇷',
      'RSD': '🇷🇸',
      'TRY': '🇹🇷',
      'RUB': '🇷🇺',
      'UAH': '🇺🇦',
      'ILS': '🇮🇱',
      'QAR': '🇶🇦',
      'KWD': '🇰🇼',
      'BHD': '🇧🇭',
      'OMR': '🇴🇲',
      'JOD': '🇯🇴',
      'LBP': '🇱🇧',
      'PKR': '🇵🇰',
      'BDT': '🇧🇩',
      'LKR': '🇱🇰',
      'NPR': '🇳🇵',
      'AFN': '🇦🇫',
      'THB': '🇹🇭',
      'VND': '🇻🇳',
      'IDR': '🇮🇩',
      'MYR': '🇲🇾',
      'PHP': '🇵🇭',
      'TWD': '🇹🇼',
      'MXN': '🇲🇽',
      'ARS': '🇦🇷',
      'CLP': '🇨🇱',
      'COP': '🇨🇴',
      'PEN': '🇵🇪',
      'UYU': '🇺🇾',
      'PYG': '🇵🇾',
      'BOB': '🇧🇴',
      'VES': '🇻🇪',
      'GYD': '🇬🇾',
      'SRD': '🇸🇷',
      'DZD': '🇩🇿',
      'TND': '🇹🇳',
      'LYD': '🇱🇾',
      'SDG': '🇸🇩',
      'ETB': '🇪🇹',
      'KES': '🇰🇪',
      'UGX': '🇺🇬',
      'TZS': '🇹🇿',
      'GHS': '🇬🇭',
      'NGN': '🇳🇬',
      'BWP': '🇧🇼',
      'NAD': '🇳🇦',
      'ZWL': '🇿🇼',
      'ZMW': '🇿🇲',
      'MWK': '🇲🇼',
      'MZN': '🇲🇿',
      'AOA': '🇦🇴',
      'XAF': '🇨🇲',
      'XOF': '🇸🇳',
      'CDF': '🇨🇩',
      'STN': '🇸🇹',
      'GNF': '🇬🇳',
      'SLE': '🇸🇱',
      'LRD': '🇱🇷',
      'GMD': '🇬🇲',
      'MRU': '🇲🇷',
      'CVE': '🇨🇻',
      'KMF': '🇰🇲',
      'SCR': '🇸🇨',
      'MUR': '🇲🇺',
      'MGA': '🇲🇬',
      'LSL': '🇱🇸',
      'SZL': '🇸🇿',
      'BYN': '🇧🇾',
      'MDL': '🇲🇩',
      'GEL': '🇬🇪',
      'AMD': '🇦🇲',
      'AZN': '🇦🇿',
      'KZT': '🇰🇿',
      'UZS': '🇺🇿',
      'KGS': '🇰🇬',
      'TJS': '🇹🇯',
      'TMT': '🇹🇲',
      'MVR': '🇲🇻',
      'MMK': '🇲🇲',
      'LAK': '🇱🇦',
      'KHR': '🇰🇭',
      'BND': '🇧🇳',
      'MOP': '🇲🇴',
      'MNT': '🇲🇳',
      'KPW': '🇰🇵',
      'YER': '🇾🇪',
      'IQD': '🇮🇶',
      'IRR': '🇮🇷',
      'SYP': '🇸🇾',
      'ISK': '🇮🇸',
      'ALL': '🇦🇱',
      'MKD': '🇲🇰',
      'BAM': '🇧🇦'
    };

    return Object.keys(this.baseRates).map(code => ({
      code,
      name: currencyNames[code] || code,
      symbol: symbols[code] || code,
      flag: flags[code] || '🌍'
    }));
  }

  // Mettre à jour les taux de change (pour une future intégration API)
  public async updateRates(): Promise<void> {
    try {
      // Ici on pourrait intégrer une vraie API de taux de change
      // Pour l'instant, on utilise les taux statiques
      console.log('Currency rates updated');
    } catch (error) {
      console.error('Failed to update currency rates:', error);
    }
  }
}

const currencyService = new CurrencyService();
export default currencyService;